### ISSUE TITLE
Captcha doesn't show a captcha

### ISSUE THREAD

**Issue by brendanbabb** [codeforanchorage/collective-development#23]
There is no captcha image. Check catptcha functionality. It doesn't stop you and it doesn't test the captcha entry.

**Comment by tescher** [comment]
Looks like someone was trying to be clever with bots, but I think all it will do is confuse the user. If any data is entered in the field it says "Welcome!" and takes you right back. I suggest removing it and letting the gotcha field right below it filter the bots. If you are cool with that I can make the change.

```
        # This is a honeypot and we act like it was successful
        if form.captcha.data:
            flash(_("Welcome to the website!"), 'success')
            return redirect(form.next.data or url_for('schools.home'))
```

**Comment by thermokarst** [comment]
@tescher: The complete context for the honeypot code (motivation and implementation) can be found here - https://github.com/sdockray/tps/commit/54dae4732c2d80c8ecec8a597c016f0d4bb8aa0f

Sounds like any changes that wind up happening should probably be communicated back to @sdockray, since this project was forked from him.
